"""
Channel-Specific Response Formatters

This module handles formatting responses appropriately for each channel.
"""

from enum import Enum
from typing import Optional
import logging

logger = logging.getLogger(__name__)


class Channel(str, Enum):
    """Supported communication channels."""
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


# Response length limits by channel
CHANNEL_LIMITS = {
    Channel.EMAIL: {"max_words": 500, "min_words": 50},
    Channel.WHATSAPP: {"max_chars": 1600, "preferred_chars": 300},
    Channel.WEB_FORM: {"max_words": 300, "min_words": 30},
}


def format_for_channel(
    message: str,
    channel: str,
    ticket_id: str,
    customer_name: Optional[str] = None,
) -> str:
    """
    Format response message for the appropriate channel.

    Args:
        message: Base message content
        channel: Channel type (email, whatsapp, web_form)
        ticket_id: Ticket reference ID
        customer_name: Optional customer name for personalization

    Returns:
        Formatted message for the channel
    """
    channel_enum = Channel(channel.lower())
    
    if channel_enum == Channel.EMAIL:
        return format_email_response(message, ticket_id, customer_name)
    elif channel_enum == Channel.WHATSAPP:
        return format_whatsapp_response(message)
    else:  # WEB_FORM
        return format_webform_response(message, ticket_id)


def format_email_response(
    message: str,
    ticket_id: str,
    customer_name: Optional[str] = None,
) -> str:
    """
    Format response for email channel.

    Features:
    - Formal greeting with customer name
    - Professional tone
    - Detailed response (up to 500 words)
    - Proper signature
    - Ticket reference

    Args:
        message: Base message content
        ticket_id: Ticket reference ID
        customer_name: Optional customer name

    Returns:
        Formatted email response
    """
    # Use generic greeting if no name provided
    name = customer_name or "Valued Customer"
    
    # Ensure message is within word limit
    words = message.split()
    if len(words) > 500:
        message = " ".join(words[:500]) + "..."
        logger.info(f"Truncated email response from {len(words)} to 500 words")
    
    return f"""Dear {name},

Thank you for reaching out to TaskFlow Pro Support.

{message}

If you have any further questions, please don't hesitate to reply to this email.

Best regards,
TaskFlow Pro AI Support Team
---
Ticket Reference: #{ticket_id}
This response was generated by our AI assistant. For complex issues, you can request human support."""


def format_whatsapp_response(message: str) -> str:
    """
    Format response for WhatsApp channel.

    Features:
    - Concise and conversational
    - Preferred under 300 characters
    - Hard limit 1600 characters
    - Emoji for friendliness
    - Quick reply hint

    Args:
        message: Base message content

    Returns:
        Formatted WhatsApp response (possibly split into multiple messages)
    """
    # Hard limit for WhatsApp
    max_length = 1600
    preferred_length = 300
    
    # Truncate if over hard limit
    if len(message) > max_length:
        message = message[:max_length - 3] + "..."
        logger.info(f"Truncated WhatsApp response to {max_length} characters")
    
    # Add friendly emoji and reply hint
    formatted = f"{message}\n\n📱 Reply for more help or type 'human' for live support."
    
    return formatted


def format_webform_response(message: str, ticket_id: str) -> str:
    """
    Format response for web form channel.

    Features:
    - Semi-formal tone
    - Balanced detail (up to 300 words)
    - Ticket reference
    - Portal link hint

    Args:
        message: Base message content
        ticket_id: Ticket reference ID

    Returns:
        Formatted web form response
    """
    # Ensure message is within word limit
    words = message.split()
    if len(words) > 300:
        message = " ".join(words[:300]) + "..."
        logger.info(f"Truncated web form response from {len(words)} to 300 words")
    
    return f"""{message}

---
Need more help? Reply to this message or visit our support portal.
Ticket Reference: #{ticket_id}"""


def truncate_for_channel(message: str, channel: str) -> str:
    """
    Truncate message to fit channel limits.

    Args:
        message: Message to truncate
        channel: Channel type

    Returns:
        Truncated message
    """
    channel_enum = Channel(channel.lower())
    limits = CHANNEL_LIMITS.get(channel_enum)
    
    if not limits:
        return message
    
    if "max_chars" in limits:
        # Character-based limit (WhatsApp)
        max_chars = limits["max_chars"]
        if len(message) > max_chars:
            return message[:max_chars - 3] + "..."
    elif "max_words" in limits:
        # Word-based limit (Email, Web)
        max_words = limits["max_words"]
        words = message.split()
        if len(words) > max_words:
            return " ".join(words[:max_words]) + "..."
    
    return message


def split_whatsapp_message(message: str, max_length: int = 1600) -> list[str]:
    """
    Split long message into multiple WhatsApp messages.

    Args:
        message: Message to split
        max_length: Maximum characters per message

    Returns:
        List of message parts
    """
    if len(message) <= max_length:
        return [message]
    
    messages = []
    
    while message:
        if len(message) <= max_length:
            messages.append(message)
            break
        
        # Find a good break point (sentence or word)
        break_point = message.rfind('. ', 0, max_length)
        if break_point == -1:
            break_point = message.rfind(' ', 0, max_length)
        if break_point == -1:
            break_point = max_length
        
        messages.append(message[:break_point + 1].strip())
        message = message[break_point + 1:].strip()
    
    return messages


def add_empathy_prefix(sentiment_score: float, message: str) -> str:
    """
    Add empathy prefix based on sentiment score.

    Args:
        sentiment_score: Customer sentiment (-1.0 to 1.0)
        message: Original response message

    Returns:
        Message with empathy prefix if needed
    """
    if sentiment_score < -0.5:
        # Very negative - show strong empathy
        prefix = "I completely understand your frustration, and I sincerely apologize for the inconvenience you've experienced. "
    elif sentiment_score < 0:
        # Somewhat negative - show understanding
        prefix = "I understand your concern, and I'm here to help. "
    elif sentiment_score > 0.5:
        # Very positive - match enthusiasm
        prefix = "Great to hear from you! "
    else:
        # Neutral - no prefix needed
        return message
    
    return prefix + message
